const fk = require("./index");

/*
 * Lorem ipsum and translation from: https://lipsum.com/
 */
const LOREM_IPSUM = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

const TRANSLATED_LOREM_IPSUM = `"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?`

const MOBY_DICK = `Call me Ishmael. Some years ago- never mind how long precisely- having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off- then, I account it high time to get to sea as soon as I can. This is my substitute for pistol and ball. With a philosophical flourish Cato throws himself upon his sword; I quietly take to the ship. There is nothing surprising in this. If they but knew it, almost all men in their degree, some time or other, cherish very nearly the same feelings towards the ocean with me.`

const THREE_LITTLE_PIGS = `Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes. The first little pig was very lazy. He didn't want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.`

const THE_WAR_OF_THE_WORLDS = `No one would have believed, in the last years of the nineteenth century, that human affairs were being watched keenly and closely by intelligences greater than man’s and yet as mortal as his own; that as men busied themselves about their affairs they were scrutinized and studied, perhaps almost as narrowly as a man with a microscope might scrutinize the transient creatures that swarm and multiply in a drop of water. With infinite complacency men went to and fro over this globe about their little affairs, serene in their assurance of their empire over matter. It is possible that the infusoria under the microscope do the same. No one gave a thought to the older worlds of space as sources of human danger, or thought of them only to dismiss the idea of life upon them as impossible or improbable. It is curious to recall some of the mental habits of those departed days. At most, terrestrial men fancied there might be other men upon Mars, perhaps inferior to themselves and ready to welcome a missionary enterprise. Yet, across the gulf of space, minds that are to our minds as ours are to those of the beasts that perish, intellects vast and cool and unsympathetic, regarded this earth with envious eyes, and slowly and surely drew their plans against us. And early in the twentieth century came the great disillusionment.`

/*
 * Youth by Isaac Asimov
 */
const YOUTH = `There was a spatter of pebbles against the window and the youngster stirred in his sleep. Another, and he was awake. He sat up stiffly in bed. Seconds passed while he interpreted his strange surroundings. He wasn't in his own home, of course. This was out in the country. It was colder than it should be and there was green at the window. "Slim!" The call was a hoarse, urgent whisper, and the youngster bounded to the open window. Slim wasn't his real name, but the new friend he had met the day before had needed only one look at his slight figure to say, "You're Slim." He added, "I'm Red." Red wasn't his real name, either, but its appropriateness was obvious. They were friends instantly with the quick unquestioning friendship of young ones not yet quite in adolescence, before even the first stains of adulthood began to make their appearance. Slim cried, "Hi, Red!" and waved cheerfully, still blinking the sleep out of himself. Red kept to his croaking whisper, "Quiet! You want to wake somebody?" Slim noticed all at once that the sun scarcely topped the low hills in the east, that the shadows were long and soft, and that the grass was wet.`

console.log("Lorem ipsum grade level: ", fk.getGradeLevel(LOREM_IPSUM));
console.log("Lorem ipsum reading ease: : ", fk.getReadingEase(LOREM_IPSUM));
console.log("Lorem ipsum (translated) grade level: ", fk.getGradeLevel(TRANSLATED_LOREM_IPSUM));
console.log("Lorem ipsum (translated) reading ease: : ", fk.getReadingEase(TRANSLATED_LOREM_IPSUM));
console.log("Moby Dick grade level: ", fk.getGradeLevel(MOBY_DICK));
console.log("Moby Dick reading ease: : ", fk.getReadingEase(MOBY_DICK));
console.log("Three Little Pigs grade level: ", fk.getGradeLevel(THREE_LITTLE_PIGS));
console.log("Three Little Pigs reading ease: : ", fk.getReadingEase(THREE_LITTLE_PIGS));
console.log("The War of the Worlds grade level: ", fk.getGradeLevel(THE_WAR_OF_THE_WORLDS));
console.log("The War of the Worlds reading ease: : ", fk.getReadingEase(THE_WAR_OF_THE_WORLDS));
console.log("Youth grade level: ", fk.getGradeLevel(YOUTH));
console.log("Youth reading ease: : ", fk.getReadingEase(YOUTH));